### ISSUE TITLE
failed to locate @import file jeet.styl

### ISSUE THREAD

**Issue by gabalicious** [FrontendMasters/angular-components#11]
Not sure Why this is happening. This happens in steps 2 and after.

I get an error after running npm start...

`
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jgaba/.nvm/versions/node/v5.6.0/bin/node',
1 verbose cli   '/Users/jgaba/.nvm/versions/node/v5.6.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ng-blog@1.0.0~prestart: ng-blog@1.0.0
6 silly lifecycle ng-blog@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle ng-blog@1.0.0~start: ng-blog@1.0.0
8 verbose lifecycle ng-blog@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ng-blog@1.0.0~start: PATH: /Users/jgaba/.nvm/versions/node/v5.6.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/jgaba/development/angular-components/node_modules/.bin:/Users/jgaba/.nvm/versions/node/v5.6.0/bin:/usr/local/opt/php70/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle ng-blog@1.0.0~start: CWD: /Users/jgaba/development/angular-components
11 silly lifecycle ng-blog@1.0.0~start: Args: [ '-c', 'gulp' ]
12 silly lifecycle ng-blog@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle ng-blog@1.0.0~start: Failed to exec start script
14 verbose stack Error: ng-blog@1.0.0 start:`gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/jgaba/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/jgaba/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid ng-blog@1.0.0
16 verbose cwd /Users/jgaba/development/angular-components
17 error Darwin 15.5.0
18 error argv "/Users/jgaba/.nvm/versions/node/v5.6.0/bin/node" "/Users/jgaba/.nvm/versions/node/v5.6.0/bin/npm" "start"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error ng-blog@1.0.0 start:`gulp`
22 error Exit status 1
23 error Failed at the ng-blog@1.0.0 start script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ng-blog package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ng-blog
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ng-blog
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

`

Node version: v5.6.0
NPM Version: 3.6.0

Let me know if I haven't provided enough information.

**Comment by gabalicious** [comment]
Looks like an issue with Jeet 6.1.2. 

I fixed it thanks to https://github.com/mojotech/jeet/issues/129#issuecomment-228571314: 
npm install jeet@6.1.1 --save-dev
