### ISSUE TITLE
Update the stylus dependency.

### ISSUE THREAD

**Issue by toddmagnusson** [FrontendMasters/angular-components#14]
Running on Windows 10 Pro/NT

Kept getting this error right before build:
`Potentially unhandled rejection [4] Error: callback(): The callback was already called.
    at context.callback (C:\Users\Business\Learning\angularjs1x-components\node_modules\webpack-core\lib\NormalModuleMixin.js:143:11)
    at tryCatchReject (C:\Users\Business\Learning\angularjs1x-components\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 (C:\Users\Business\Learning\angularjs1x-components\node_modules\when\lib\makePromise.js:799:4)
    at Rejected.when (C:\Users\Business\Learning\angularjs1x-components\node_modules\when\lib\makePromise.js:623:4)
    at Pending.run (C:\Users\Business\Learning\angularjs1x-components\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain (C:\Users\Business\Learning\angularjs1x-components\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\Business\Learning\angularjs1x-components\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

I was also getting the Jeet issue that has already been addressed here. On Windows I had to manually update the Stylus dependency to the latest release to get build to load and watch to start.

**Comment by villematti** [comment]
For me this issue was caused by stylus-loader. When I used version 1.2.1, it got fixed.

**Comment by dane-king** [comment]
I'm getting this issue when I use ^1.2.1, playing around with it, if I go past 1.3 it gives me the same error. If fixed it by using ~1.2.1

**Comment by jellydonut** [comment]
I am getting that error too. i have tried changing the stylus-loader: ~1.2.1
