### ISSUE TITLE
bug (step-2) 

### ISSUE THREAD

**Issue by naotoyamaguchi** [FrontendMasters/angular-components#15]
Trying to npm start (after npm installing) the step-2-fix branch after importing angular-ui-router. Same error appears when trying to npm start step-3-fix as well.

`[17:19:34] Using gulpfile ~/Documents/AngularJS/angular-components/gulpfile.js
[17:19:34] Starting 'default'...
[17:19:34] Starting 'todo'...
[17:19:34] Totals
[17:19:34] Finished 'todo' after 29 ms
[17:19:34] Starting 'build'...
Potentially unhandled rejection [4] Error: callback(): The callback was already called.
    at context.callback (/Users/naotoy/Documents/AngularJS/angular-components/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at tryCatchReject (/Users/naotoy/Documents/AngularJS/angular-components/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/Users/naotoy/Documents/AngularJS/angular-components/node_modules/when/lib/makePromise.js:799:4)
    at Rejected.when (/Users/naotoy/Documents/AngularJS/angular-components/node_modules/when/lib/makePromise.js:623:4)
    at Pending.run (/Users/naotoy/Documents/AngularJS/angular-components/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/Users/naotoy/Documents/AngularJS/angular-components/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/naotoy/Documents/AngularJS/angular-components/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by nissaw** [comment]
Had a similar error that was fixed by reverting to node v0.12.1 for this project.
